package Telas;

import entidades.Atleta;
import estruturasDeDados.*;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class CampeonatoAtletismo2024 extends javax.swing.JFrame {
        Pilha p1;
        Fila f1;
    public CampeonatoAtletismo2024() {
        p1 = new Pilha();
        f1 = new Fila();
        initComponents();
        cadastrarDadosIniciais();
    }
    public void cadastrarDadosIniciais() {

    Atleta a1 = new Atleta("Laura Stewart", "USA", 'F', 10.65);
    p1.push(a1);
    Atleta a2 = new Atleta("Francesco Laurentis", "Itália", 'M', 10.98);
    f1.enqueue(a2);
    Atleta a3 = new Atleta("Lívia Alves", "Brasil", 'F', 11.32);
    p1.push(a3);
    Atleta a4 = new Atleta("Marcos Silva", "Brasil", 'M', 9.98);
    f1.enqueue(a4);
    Atleta a5 = new Atleta("Fernando Sotomayor", "Cuba", 'M', 11.42);
    f1.enqueue(a5);
    Atleta a6 = new Atleta("Miley Marley", "Jamaica", 'F', 10.58);
    p1.push(a6);
    Atleta a7 = new Atleta("Pierre Depardiu", "França", 'M', 11.78);
    f1.enqueue(a7);
    Atleta a8 = new Atleta("Renata Medeiros", "Portugal", 'F', 12.14);   
    p1.push(a8);
    //agora, adicionar aqui os atletas anteriores nas estruturas 

    //de dados utilizadas neste projeto:  

  }
    public void bubbleSort(Atleta[] x){
        for (int i = 0; i < x.length - 1; i++) {
            for (int j = 0; j < x.length-1-i; j++) {
                if(x[j].getName().compareToIgnoreCase(x[j+1].getName()) > 0){
                    Atleta temp = x[j];
                    x[j] = x[j+1];
                    x[j+1] = temp;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pais = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tempo = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        listaGeral = new javax.swing.JButton();
        mediaGeral = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mediaHomens = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        MostraPilha = new javax.swing.JButton();
        MostraFila = new javax.swing.JButton();
        RetiraPilha = new javax.swing.JButton();
        RetiraFila = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campeonato Atletismo");
        setResizable(false);

        jLabel1.setText("Nome do Atleta:");

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel2.setText("País:");

        jLabel3.setText("Sexo:");

        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione:", "Masculino", "Feminino" }));

        jLabel4.setText("Tempo");

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        listaGeral.setText("ListarCadastro");
        listaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaGeralActionPerformed(evt);
            }
        });

        mediaGeral.setText("Média Geral");
        mediaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaGeralActionPerformed(evt);
            }
        });

        jButton4.setText("Mulher melhor Tempo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        mediaHomens.setText("Média homens brasileiros ");
        mediaHomens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaHomensActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setText("AUTORES");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        MostraPilha.setText("Mostrar Pilha");
        MostraPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraPilhaActionPerformed(evt);
            }
        });

        MostraFila.setText("Mostrar Fila");
        MostraFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraFilaActionPerformed(evt);
            }
        });

        RetiraPilha.setText("Retirar da Pilha");
        RetiraPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiraPilhaActionPerformed(evt);
            }
        });

        RetiraFila.setText("Retirar da Fila");
        RetiraFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetiraFilaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nome)
                                            .addComponent(pais)
                                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tempo, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(669, 669, 669)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MostraPilha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MostraFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(cadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(listaGeral)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mediaGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RetiraPilha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RetiraFila, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mediaHomens, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(listaGeral)
                    .addComponent(mediaGeral)
                    .addComponent(jButton4)
                    .addComponent(mediaHomens)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostraPilha)
                    .addComponent(MostraFila)
                    .addComponent(RetiraPilha)
                    .addComponent(RetiraFila))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
       // NumberFormatException
        try {
            String Name = this.nome.getText();
            String Country = this.pais.getText();
            String sex = (String)this.sexo.getSelectedItem();
            Double Time = Double.valueOf(this.tempo.getText());
            Atleta t1;
        if(!("".equals(Name)) && !("".equals(Country)) && !("Selecione:".equals(sex))){
            if(sex.equalsIgnoreCase("masculino")){
            t1 = new Atleta(Name,Country,'M',Time);
            f1.enqueue(t1);
        }else{
            t1 = new Atleta(Name,Country,'F',Time);
            p1.push(t1);
        }
        JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso");
            nome.setText("");
            pais.setText("");
            sexo.setSelectedIndex(0);
            tempo.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todas as informações");
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um tempo válido");
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void listaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaGeralActionPerformed
        Atleta[] listaFem =  (Atleta[]) p1.toArray();
        Atleta[] listaMas =  (Atleta[]) f1.toArray();             
        String msg = "Mulheres: \n";
        if(listaFem!= null){
            bubbleSort(listaFem);
            for (int i = 0; i < listaFem.length; i++) {
            msg += listaFem[i].toString();
            if(i!= listaFem.length - 1){
                msg+= "\n";
            }
        }
        }else{
            msg+= "Pilha vazia";
        }
        msg += "\nHomens: \n";
        if(listaMas != null){
            bubbleSort(listaMas);
            for (int i = 0; i < listaMas.length; i++) {
            msg += listaMas[i].toString();
            if(i!= listaMas.length - 1){
                msg+= "\n";
            }
        }
        }else{
            msg+= "Fila vazia";
        }
        jTextArea1.setText(msg);
    }//GEN-LAST:event_listaGeralActionPerformed

    private void mediaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaGeralActionPerformed
        
        Double media = 0.0;
        Atleta[] listaFem = p1.toArray();
        Atleta[] listaMas = f1.toArray();
        String msg = "";
        if(listaFem == null){
            msg+="\n A pilha está vazia";
        }
        if(listaMas == null){
            msg +=" \n A fila está vazia";
        }
        if(listaFem == null){
            listaFem = new Atleta[0];
        }
        if(listaMas == null){
            listaMas = new Atleta[0];
        }
        Integer total = listaFem.length+listaMas.length;
        for (int i = 0; i < listaFem.length; i++) {
            media += listaFem[i].getTempo();
        }
        for (int i = 0; i < listaMas.length; i++) {
            media += listaMas[i].getTempo();
        }
        media = media/total;
        Double result = (double)Math.round(media*100)/100;
        msg += "\nA média dos tempos é: "+ result;
        

        JOptionPane.showMessageDialog(null, msg );
    }//GEN-LAST:event_mediaGeralActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Atleta[] lista = p1.toArray();
        if(lista == null){
            JOptionPane.showMessageDialog(null, "Não há mulheres cadastradas");
        }else{
            double menor = lista[0].getTempo();
            int posicao = 0;
            for (int i = 0; i < lista.length; i++) {
                if(lista[i].getTempo() < menor){
                    menor = lista[i].getTempo();
                    posicao = i;
                }
            }
            String msg = "\nA mulher com melhor tempo é: \n" + lista[posicao].toString();
            jTextArea1.setText(msg); 
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mediaHomensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaHomensActionPerformed
        Atleta[] lista = f1.toArray();
        if(lista == null){
            JOptionPane.showMessageDialog(null, "Não há homens cadastrados");
        }else{
            double soma = 0;
            int contador = 0;
            for (int i = 0; i < lista.length; i++) {
                if(lista[i].getPais().equalsIgnoreCase("brasil")){
                    soma+= lista[i].getTempo();
                    contador+=1;
                }
            }
            JOptionPane.showMessageDialog(null, "A média dos homens brasileiros é: "+ (soma/contador));
        }
        
    }//GEN-LAST:event_mediaHomensActionPerformed

    private void MostraPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraPilhaActionPerformed
        if(p1.isEmpty()){
            jTextArea1.setText("");
            JOptionPane.showMessageDialog(null, "A pilha está vazia");
        }else{
            jTextArea1.setText(p1.toString());
        }
    }//GEN-LAST:event_MostraPilhaActionPerformed

    private void MostraFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraFilaActionPerformed
        if(f1.isEmpty()){
            jTextArea1.setText("");
            JOptionPane.showMessageDialog(null, "A Fila está vazia");
        }else{
            jTextArea1.setText(f1.toString());
        }
    }//GEN-LAST:event_MostraFilaActionPerformed

    private void RetiraPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiraPilhaActionPerformed
        if(p1.isEmpty()){
            jTextArea1.setText("");
            JOptionPane.showMessageDialog(null, "A pilha está vazia");
        }else{
            Atleta a2 = (Atleta) p1.pop();
            jTextArea1.setText("Retirado ultimo da pilha: \n"+ a2.toString()+ "\n" + p1.toString());
        }
    }//GEN-LAST:event_RetiraPilhaActionPerformed

    private void RetiraFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetiraFilaActionPerformed
        if(f1.isEmpty()){
            jTextArea1.setText("");
            JOptionPane.showMessageDialog(null, "A fila está vazia");
        }else{
            Atleta a3 = (Atleta) f1.dequeue();
            jTextArea1.setText("Retirado primeiro da fila: \n"+ a3.toString() + "\n" +f1.toString());
        }
    }//GEN-LAST:event_RetiraFilaActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Autores a1 = new Autores();
        a1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampeonatoAtletismo2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampeonatoAtletismo2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampeonatoAtletismo2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampeonatoAtletismo2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampeonatoAtletismo2024().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostraFila;
    private javax.swing.JButton MostraPilha;
    private javax.swing.JToggleButton RetiraFila;
    private javax.swing.JButton RetiraPilha;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton listaGeral;
    private javax.swing.JButton mediaGeral;
    private javax.swing.JButton mediaHomens;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField pais;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField tempo;
    // End of variables declaration//GEN-END:variables
}
